### Concatenation of two dataframes

In [1]:
import pandas as pd

In [ ]:
# when the name of column is different in both the dataframes
df1 = pd.DataFrame({
    'id1': [1,2,3,4],
    'name': ['Dhruv', 'Amit', 'Educosys', 'Youtube']
})

df2 = pd.DataFrame({
    'id2': [3,4,5,6],
    'course': ['GenAI', 'CPP', 'HLD', 'LLD']
})

inner_result = pd.concat([df1, df2], axis = 0)
inner_result

   id1      name  id2 course
0  1.0     Dhruv  NaN    NaN
1  2.0      Amit  NaN    NaN
2  3.0  Educosys  NaN    NaN
3  4.0   Youtube  NaN    NaN
0  NaN       NaN  3.0  GenAI
1  NaN       NaN  4.0    CPP
2  NaN       NaN  5.0    HLD
3  NaN       NaN  6.0    LLD

In [ ]:
inner_result = pd.concat([df1, df2], axis = 0, ignore_index = True) #ignore_index is used to keep the id sequentially incremented
inner_result

   id1      name  id2 course
0  1.0     Dhruv  NaN    NaN
1  2.0      Amit  NaN    NaN
2  3.0  Educosys  NaN    NaN
3  4.0   Youtube  NaN    NaN
4  NaN       NaN  3.0  GenAI
5  NaN       NaN  4.0    CPP
6  NaN       NaN  5.0    HLD
7  NaN       NaN  6.0    LLD

In [5]:
result = pd.concat([df1, df2], axis = 0, keys = ['df1', 'df2'])
result

       id1      name  id2 course
df1 0  1.0     Dhruv  NaN    NaN
    1  2.0      Amit  NaN    NaN
    2  3.0  Educosys  NaN    NaN
    3  4.0   Youtube  NaN    NaN
df2 0  NaN       NaN  3.0  GenAI
    1  NaN       NaN  4.0    CPP
    2  NaN       NaN  5.0    HLD
    3  NaN       NaN  6.0    LLD

In [6]:
result2 = pd.concat([df1, df2], axis = 1)
result2

   id1      name  id2 course
0    1     Dhruv    3  GenAI
1    2      Amit    4    CPP
2    3  Educosys    5    HLD
3    4   Youtube    6    LLD