### Data Filtering Methods

In [3]:
import pandas as pd

In [4]:
ob_data = pd.read_csv('./obesity_pandas_practice.csv')

In [5]:
ob_data.loc[ob_data['Weight'] < 50]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
29,Female,37.0,1.52,46.1,yes,no,2.4,3.1,Always,no,1.8,no,2.1,1.2,no,Automobile,Normal_Weight
31,Female,29.0,1.57,43.1,NaN,yes,1.9,1.3,Sometimes,no,3.4,no,1.4,1.6,no,Public_Transportation,Insufficient_Weight
40,Female,50.0,1.55,46.1,yes,yes,1.7,1.6,Sometimes,no,2.8,no,2.4,1.6,Frequently,Public_Transportation,Normal_Weight
42,Male,27.0,1.51,45.4,yes,yes,1.9,1.3,no,no,3.5,no,2.7,1.2,no,Walking,Normal_Weight
66,Female,38.0,1.56,45.1,no,yes,2.0,1.7,no,no,1.9,no,2.9,0.9,Frequently,Automobile,Normal_Weight
68,Female,27.0,1.53,45.9,no,yes,2.0,3.7,Sometimes,no,2.2,yes,2.2,0.9,no,Automobile,Normal_Weight
77,Female,49.0,1.53,48.5,no,yes,2.8,2.3,no,no,2.8,no,2.3,1.2,Frequently,Motorbike,Normal_Weight
79,Male,40.0,1.55,49.1,yes,no,2.5,2.1,Frequently,no,2.1,yes,0.2,1.1,Always,NaN,Normal_Weight
90,Female,37.0,1.55,46.0,yes,yes,1.7,3.6,Frequently,no,1.1,no,0.1,0.1,Always,Public_Transportation,Normal_Weight
97,Female,58.0,1.67,47.2,no,yes,1.2,3.3,Frequently,no,1.2,no,1.8,1.4,Frequently,Public_Transportation,Insufficient_Weight

In [6]:
ob_data.loc[(ob_data['Weight'] < 50) & (ob_data['Obesity'] == 'Normal_Weight')]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
29,Female,37.0,1.52,46.1,yes,no,2.4,3.1,Always,no,1.8,no,2.1,1.2,no,Automobile,Normal_Weight
40,Female,50.0,1.55,46.1,yes,yes,1.7,1.6,Sometimes,no,2.8,no,2.4,1.6,Frequently,Public_Transportation,Normal_Weight
42,Male,27.0,1.51,45.4,yes,yes,1.9,1.3,no,no,3.5,no,2.7,1.2,no,Walking,Normal_Weight
66,Female,38.0,1.56,45.1,no,yes,2.0,1.7,no,no,1.9,no,2.9,0.9,Frequently,Automobile,Normal_Weight
68,Female,27.0,1.53,45.9,no,yes,2.0,3.7,Sometimes,no,2.2,yes,2.2,0.9,no,Automobile,Normal_Weight
77,Female,49.0,1.53,48.5,no,yes,2.8,2.3,no,no,2.8,no,2.3,1.2,Frequently,Motorbike,Normal_Weight
79,Male,40.0,1.55,49.1,yes,no,2.5,2.1,Frequently,no,2.1,yes,0.2,1.1,Always,NaN,Normal_Weight
90,Female,37.0,1.55,46.0,yes,yes,1.7,3.6,Frequently,no,1.1,no,0.1,0.1,Always,Public_Transportation,Normal_Weight

In [8]:
ob_data.loc[ob_data['Obesity'].str.contains('Normal')]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Male,29.0,1.65,57.1,no,yes,1.5,2.1,Always,no,3.3,no,0.8,1.5,Frequently,Motorbike,Normal_Weight
1,Male,33.0,1.88,80.8,yes,yes,1.0,2.5,Sometimes,no,2.8,no,0.0,1.7,Sometimes,Public_Transportation,Normal_Weight
2,Male,43.0,1.79,72.2,yes,yes,2.0,3.6,Sometimes,yes,2.5,no,0.5,0.9,no,Automobile,Normal_Weight
6,Female,53.0,1.52,56.7,yes,no,2.6,3.5,Sometimes,no,1.3,no,2.6,1.3,Frequently,Automobile,Normal_Weight
7,Female,NaN,1.85,79.8,no,no,2.9,1.2,Sometimes,no,2.2,no,1.6,0.7,Sometimes,Motorbike,Normal_Weight
9,Male,54.0,1.78,71.0,no,no,2.6,3.1,Always,no,2.3,yes,0.9,1.0,Sometimes,Walking,Normal_Weight
10,Male,40.0,1.51,52.0,yes,no,2.2,4.0,Sometimes,no,1.4,no,2.5,0.2,Sometimes,Walking,Normal_Weight
11,Male,27.0,1.89,73.2,no,no,2.0,3.7,no,no,3.1,yes,2.3,0.8,no,Walking,Normal_Weight
12,Female,22.0,1.83,79.3,no,yes,1.8,2.7,Always,no,3.1,no,0.7,0.4,Sometimes,Motorbike,Normal_Weight
17,Male,36.0,1.71,70.6,yes,no,2.2,3.2,Frequently,no,1.9,no,2.2,1.9,Always,Automobile,Normal_Weight
19,Male,18.0,1.62,63.9,yes,no,2.2,3.2,Always,no,2.0,no,2.6,1.7,Always,Automobile,Normal_Weight
20,Female,22.0,1.74,75.1,no,no,2.3,2.6,Frequently,no,2.8,no,2.9,1.3,no,Motorbike,Normal_Weight
22,Male,33.0,1.62,61.8,yes,no,1.2,3.5,Always,no,2.1,no,1.3,1.5,Always,Public_Transportation,Normal_Weight
24,Male,33.0,1.68,68.7,yes,yes,2.1,3.9,Always,no,1.2,no,1.0,1.1,no,Automobile,Normal_Weight
25,Female,19.0,1.81,61.1,no,yes,1.9,3.1,Always,no,1.0,no,2.2,1.0,Frequently,Public_Transportation,Normal_Weight
29,Female,37.0,1.52,46.1,yes,no,2.4,3.1,Always,no,1.8,no,2.1,1.2,no,Automobile,Normal_Weight
34,Female,50.0,1.89,69.8,yes,yes,1.1,2.0,Frequently,no,2.3,no,0.6,0.6,Sometimes,Automobile,Normal_Weight
35,Male,60.0,1.82,71.8,yes,no,1.1,2.8,Sometimes,yes,1.2,yes,0.3,0.7,Always,Walking,Normal_Weight
36,Female,54.0,1.62,65.6,no,yes,2.2,2.1,no,no,3.4,no,0.5,0.8,Sometimes,Walking,Normal_Weight
37,Male,29.0,1.54,52.1,no,no,1.7,2.4,Sometimes,no,2.9,yes,1.4,0.9,Sometimes,Public_Transportation,Normal_Weight
39,Male,18.0,1.68,70.1,yes,yes,2.2,2.6,no,no,2.9,no,0.1,0.5,Sometimes,Motorbike,Normal_Weight
40,Female,50.0,1.55,46.1,yes,yes,1.7,1.6,Sometimes,no,2.8,no,2.4,1.6,Frequently,Public_Transportation,Normal_Weight
42,Male,27.0,1.51,45.4,yes,yes,1.9,1.3,no,no,3.5,no,2.7,1.2,no,Walking,Normal_Weight
44,Female,46.0,1.60,52.7,no,no,1.8,1.0,Frequently,no,2.6,no,0.6,0.7,no,Public_Transportation,Normal_Weight
45,Male,30.0,1.77,71.7,no,no,2.4,1.4,NaN,no,2.7,yes,1.4,1.0,Always,Automobile,Normal_Weight
60,Female,24.0,1.66,58.1,yes,no,1.7,3.3,Frequently,no,2.9,no,2.0,1.2,Frequently,Walking,Normal_Weight
63,Female,46.0,1.64,56.3,no,yes,1.7,3.4,no,no,2.3,no,2.2,0.5,Sometimes,Automobile,Normal_Weight
66,Female,38.0,1.56,45.1,no,yes,2.0,1.7,no,no,1.9,no,2.9,0.9,Frequently,Automobile,Normal_Weight
68,Female,27.0,1.53,45.9,no,yes,2.0,3.7,Sometimes,no,2.2,yes,2.2,0.9,no,Automobile,Normal_Weight
71,Male,41.0,1.58,50.9,yes,yes,1.0,3.0,no,no,2.1,no,0.3,0.9,Always,Motorbike,Normal_Weight
76,Female,56.0,1.81,76.2,no,yes,2.1,2.6,Always,no,2.7,no,1.0,0.8,no,Motorbike,Normal_Weight
77,Female,49.0,1.53,48.5,no,yes,2.8,2.3,no,no,2.8,no,2.3,1.2,Frequently,Motorbike,Normal_Weight
78,Male,41.0,1.64,53.9,yes,yes,1.5,2.7,Sometimes,yes,2.3,no,2.8,0.7,no,Motorbike,Normal_Weight
79,Male,40.0,1.55,49.1,yes,no,2.5,2.1,Frequently,no,2.1,yes,0.2,1.1,Always,NaN,Normal_Weight
80,Female,49.0,1.85,82.5,no,yes,2.1,2.2,Sometimes,no,3.2,no,1.6,1.6,Sometimes,Walking,Normal_Weight
84,Male,40.0,1.62,64.5,yes,yes,1.3,2.6,Frequently,no,1.0,yes,1.1,1.1,Frequently,Motorbike,Normal_Weight
86,Male,52.0,1.79,74.3,yes,yes,2.7,2.0,Frequently,no,2.0,no,2.9,0.1,no,Public_Transportation,Normal_Weight
89,Female,34.0,1.69,57.7,no,yes,2.7,1.5,Frequently,no,1.0,yes,2.5,0.5,no,Automobile,Normal_Weight
90,Female,37.0,1.55,46.0,yes,yes,1.7,3.6,Frequently,no,1.1,no,0.1,0.1,Always,Public_Transportation,Normal_Weight
92,Male,39.0,1.80,75.8,yes,yes,1.2,3.2,Frequently,no,1.1,no,2.9,0.4,Frequently,Walking,Normal_Weight
95,Male,53.0,1.70,69.8,yes,yes,2.1,3.3,Always,yes,1.7,no,1.8,0.2,Sometimes,Walking,Normal_Weight
96,Female,29.0,1.71,59.3,no,yes,2.7,3.1,no,no,2.0,no,1.8,1.2,Frequently,Motorbike,Normal_Weight
98,Male,36.0,1.51,50.8,yes,yes,2.1,1.4,Always,no,1.8,no,0.9,0.8,Always,Walking,Normal_Weight
104,Male,48.0,1.86,69.5,yes,yes,2.0,2.6,no,no,3.1,no,1.5,1.2,no,Public_Transportation,Normal_Weight
106,Female,33.0,1.66,68.3,yes,yes,2.5,2.4,Frequently,no,2.5,no,1.7,1.0,no,Walking,Normal_Weight
107,Male,22.0,1.80,60.9,no,no,2.1,2.8,Sometimes,no,1.7,yes,1.8,0.7,Sometimes,Motorbike,Normal_Weight
113,Female,40.0,1.82,65.6,yes,no,2.2,1.0,Frequently,no,3.4,no,2.2,1.5,no,Public_Transportation,Normal_Weight

In [10]:
ob_data.loc[ob_data['Obesity'].str.startswith('Nor')]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Male,29.0,1.65,57.1,no,yes,1.5,2.1,Always,no,3.3,no,0.8,1.5,Frequently,Motorbike,Normal_Weight
1,Male,33.0,1.88,80.8,yes,yes,1.0,2.5,Sometimes,no,2.8,no,0.0,1.7,Sometimes,Public_Transportation,Normal_Weight
2,Male,43.0,1.79,72.2,yes,yes,2.0,3.6,Sometimes,yes,2.5,no,0.5,0.9,no,Automobile,Normal_Weight
6,Female,53.0,1.52,56.7,yes,no,2.6,3.5,Sometimes,no,1.3,no,2.6,1.3,Frequently,Automobile,Normal_Weight
7,Female,NaN,1.85,79.8,no,no,2.9,1.2,Sometimes,no,2.2,no,1.6,0.7,Sometimes,Motorbike,Normal_Weight
9,Male,54.0,1.78,71.0,no,no,2.6,3.1,Always,no,2.3,yes,0.9,1.0,Sometimes,Walking,Normal_Weight
10,Male,40.0,1.51,52.0,yes,no,2.2,4.0,Sometimes,no,1.4,no,2.5,0.2,Sometimes,Walking,Normal_Weight
11,Male,27.0,1.89,73.2,no,no,2.0,3.7,no,no,3.1,yes,2.3,0.8,no,Walking,Normal_Weight
12,Female,22.0,1.83,79.3,no,yes,1.8,2.7,Always,no,3.1,no,0.7,0.4,Sometimes,Motorbike,Normal_Weight
17,Male,36.0,1.71,70.6,yes,no,2.2,3.2,Frequently,no,1.9,no,2.2,1.9,Always,Automobile,Normal_Weight
19,Male,18.0,1.62,63.9,yes,no,2.2,3.2,Always,no,2.0,no,2.6,1.7,Always,Automobile,Normal_Weight
20,Female,22.0,1.74,75.1,no,no,2.3,2.6,Frequently,no,2.8,no,2.9,1.3,no,Motorbike,Normal_Weight
22,Male,33.0,1.62,61.8,yes,no,1.2,3.5,Always,no,2.1,no,1.3,1.5,Always,Public_Transportation,Normal_Weight
24,Male,33.0,1.68,68.7,yes,yes,2.1,3.9,Always,no,1.2,no,1.0,1.1,no,Automobile,Normal_Weight
25,Female,19.0,1.81,61.1,no,yes,1.9,3.1,Always,no,1.0,no,2.2,1.0,Frequently,Public_Transportation,Normal_Weight
29,Female,37.0,1.52,46.1,yes,no,2.4,3.1,Always,no,1.8,no,2.1,1.2,no,Automobile,Normal_Weight
34,Female,50.0,1.89,69.8,yes,yes,1.1,2.0,Frequently,no,2.3,no,0.6,0.6,Sometimes,Automobile,Normal_Weight
35,Male,60.0,1.82,71.8,yes,no,1.1,2.8,Sometimes,yes,1.2,yes,0.3,0.7,Always,Walking,Normal_Weight
36,Female,54.0,1.62,65.6,no,yes,2.2,2.1,no,no,3.4,no,0.5,0.8,Sometimes,Walking,Normal_Weight
37,Male,29.0,1.54,52.1,no,no,1.7,2.4,Sometimes,no,2.9,yes,1.4,0.9,Sometimes,Public_Transportation,Normal_Weight
39,Male,18.0,1.68,70.1,yes,yes,2.2,2.6,no,no,2.9,no,0.1,0.5,Sometimes,Motorbike,Normal_Weight
40,Female,50.0,1.55,46.1,yes,yes,1.7,1.6,Sometimes,no,2.8,no,2.4,1.6,Frequently,Public_Transportation,Normal_Weight
42,Male,27.0,1.51,45.4,yes,yes,1.9,1.3,no,no,3.5,no,2.7,1.2,no,Walking,Normal_Weight
44,Female,46.0,1.60,52.7,no,no,1.8,1.0,Frequently,no,2.6,no,0.6,0.7,no,Public_Transportation,Normal_Weight
45,Male,30.0,1.77,71.7,no,no,2.4,1.4,NaN,no,2.7,yes,1.4,1.0,Always,Automobile,Normal_Weight
60,Female,24.0,1.66,58.1,yes,no,1.7,3.3,Frequently,no,2.9,no,2.0,1.2,Frequently,Walking,Normal_Weight
63,Female,46.0,1.64,56.3,no,yes,1.7,3.4,no,no,2.3,no,2.2,0.5,Sometimes,Automobile,Normal_Weight
66,Female,38.0,1.56,45.1,no,yes,2.0,1.7,no,no,1.9,no,2.9,0.9,Frequently,Automobile,Normal_Weight
68,Female,27.0,1.53,45.9,no,yes,2.0,3.7,Sometimes,no,2.2,yes,2.2,0.9,no,Automobile,Normal_Weight
71,Male,41.0,1.58,50.9,yes,yes,1.0,3.0,no,no,2.1,no,0.3,0.9,Always,Motorbike,Normal_Weight
76,Female,56.0,1.81,76.2,no,yes,2.1,2.6,Always,no,2.7,no,1.0,0.8,no,Motorbike,Normal_Weight
77,Female,49.0,1.53,48.5,no,yes,2.8,2.3,no,no,2.8,no,2.3,1.2,Frequently,Motorbike,Normal_Weight
78,Male,41.0,1.64,53.9,yes,yes,1.5,2.7,Sometimes,yes,2.3,no,2.8,0.7,no,Motorbike,Normal_Weight
79,Male,40.0,1.55,49.1,yes,no,2.5,2.1,Frequently,no,2.1,yes,0.2,1.1,Always,NaN,Normal_Weight
80,Female,49.0,1.85,82.5,no,yes,2.1,2.2,Sometimes,no,3.2,no,1.6,1.6,Sometimes,Walking,Normal_Weight
84,Male,40.0,1.62,64.5,yes,yes,1.3,2.6,Frequently,no,1.0,yes,1.1,1.1,Frequently,Motorbike,Normal_Weight
86,Male,52.0,1.79,74.3,yes,yes,2.7,2.0,Frequently,no,2.0,no,2.9,0.1,no,Public_Transportation,Normal_Weight
89,Female,34.0,1.69,57.7,no,yes,2.7,1.5,Frequently,no,1.0,yes,2.5,0.5,no,Automobile,Normal_Weight
90,Female,37.0,1.55,46.0,yes,yes,1.7,3.6,Frequently,no,1.1,no,0.1,0.1,Always,Public_Transportation,Normal_Weight
92,Male,39.0,1.80,75.8,yes,yes,1.2,3.2,Frequently,no,1.1,no,2.9,0.4,Frequently,Walking,Normal_Weight
95,Male,53.0,1.70,69.8,yes,yes,2.1,3.3,Always,yes,1.7,no,1.8,0.2,Sometimes,Walking,Normal_Weight
96,Female,29.0,1.71,59.3,no,yes,2.7,3.1,no,no,2.0,no,1.8,1.2,Frequently,Motorbike,Normal_Weight
98,Male,36.0,1.51,50.8,yes,yes,2.1,1.4,Always,no,1.8,no,0.9,0.8,Always,Walking,Normal_Weight
104,Male,48.0,1.86,69.5,yes,yes,2.0,2.6,no,no,3.1,no,1.5,1.2,no,Public_Transportation,Normal_Weight
106,Female,33.0,1.66,68.3,yes,yes,2.5,2.4,Frequently,no,2.5,no,1.7,1.0,no,Walking,Normal_Weight
107,Male,22.0,1.80,60.9,no,no,2.1,2.8,Sometimes,no,1.7,yes,1.8,0.7,Sometimes,Motorbike,Normal_Weight
113,Female,40.0,1.82,65.6,yes,no,2.2,1.0,Frequently,no,3.4,no,2.2,1.5,no,Public_Transportation,Normal_Weight