### Insert and Drop Methods

In [1]:
import pandas as pd

In [3]:
ob_data = pd.read_csv('./obesity_pandas_practice.csv')

In [ ]:
ob_data.insert(2, 'BMI', 20)

ValueError: cannot insert BMI, already exists

In [10]:
ob_data.head()

,Gender,Age,BMI,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Male,29.0,20,1.65,57.1,no,yes,1.5,2.1,Always,no,3.3,no,0.8,1.5,Frequently,Motorbike,Normal_Weight
1,Male,33.0,20,1.88,80.8,yes,yes,1.0,2.5,Sometimes,no,2.8,no,0.0,1.7,Sometimes,Public_Transportation,Normal_Weight
2,Male,43.0,20,1.79,72.2,yes,yes,2.0,3.6,Sometimes,yes,2.5,no,0.5,0.9,no,Automobile,Normal_Weight
3,Male,43.0,20,1.74,52.0,yes,no,2.0,1.3,Always,no,3.4,yes,1.4,0.1,Frequently,Motorbike,Insufficient_Weight
4,Male,38.0,20,1.56,63.2,yes,no,2.7,3.4,Frequently,no,2.0,no,2.8,0.3,Frequently,Motorbike,Overweight_Level_I

In [ ]:
ob_data.drop(columns = 'BMI') # doesnot change the dataframe
ob_data.head()

#to change the dataframe
ob_data = ob_data.drop(columns = 'BMI')
ob_data.head()

#OR
ob_data.drop(columns = 'BMI', inplace = True)

KeyError: "['BMI'] not found in axis"

### Deletion of column

In [19]:
del ob_data['CAEC']

In [20]:
ob_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Male,29.0,1.65,57.1,no,yes,1.5,2.1,no,3.3,no,0.8,1.5,Frequently,Motorbike,Normal_Weight
1,Male,33.0,1.88,80.8,yes,yes,1.0,2.5,no,2.8,no,0.0,1.7,Sometimes,Public_Transportation,Normal_Weight
2,Male,43.0,1.79,72.2,yes,yes,2.0,3.6,yes,2.5,no,0.5,0.9,no,Automobile,Normal_Weight
3,Male,43.0,1.74,52.0,yes,no,2.0,1.3,no,3.4,yes,1.4,0.1,Frequently,Motorbike,Insufficient_Weight
4,Male,38.0,1.56,63.2,yes,no,2.7,3.4,no,2.0,no,2.8,0.3,Frequently,Motorbike,Overweight_Level_I

### Renaming a column

In [21]:
ob_data.rename(columns = {'Obesity': 'Category '})

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Category
0,Male,29.0,1.65,57.1,no,yes,1.5,2.1,no,3.3,no,0.8,1.5,Frequently,Motorbike,Normal_Weight
1,Male,33.0,1.88,80.8,yes,yes,1.0,2.5,no,2.8,no,0.0,1.7,Sometimes,Public_Transportation,Normal_Weight
2,Male,43.0,1.79,72.2,yes,yes,2.0,3.6,yes,2.5,no,0.5,0.9,no,Automobile,Normal_Weight
3,Male,43.0,1.74,52.0,yes,no,2.0,1.3,no,3.4,yes,1.4,0.1,Frequently,Motorbike,Insufficient_Weight
4,Male,38.0,1.56,63.2,yes,no,2.7,3.4,no,2.0,no,2.8,0.3,Frequently,Motorbike,Overweight_Level_I
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,Male,56.0,1.85,92.6,yes,yes,2.0,2.7,yes,1.6,no,2.0,0.4,Sometimes,Walking,Overweight_Level_I
116,Male,59.0,1.82,89.7,no,no,1.7,3.1,no,2.5,yes,1.4,1.5,no,Motorbike,Overweight_Level_I
117,Male,56.0,1.57,93.7,no,no,2.9,2.8,yes,3.5,no,1.8,0.3,Always,Automobile,Obesity_Type_II
118,Male,31.0,1.86,94.6,yes,no,1.0,3.5,no,3.2,no,1.0,0.5,no,Motorbike,Overweight_Level_I
119,Female,48.0,1.72,89.3,no,no,1.5,3.9,no,2.5,no,1.4,1.9,Sometimes,Motorbike,Obesity_Type_I