### Updating data

In [3]:
import pandas as pd

In [4]:
ob_data = pd.read_csv('./obesity_pandas_practice.csv')

In [10]:
ob_data.loc[0, 'Age'] = 22
ob_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Male,22.0,1.65,57.1,no,yes,1.5,2.1,Always,no,3.3,no,0.8,1.5,Frequently,Motorbike,Normal_Weight
1,Male,33.0,1.88,80.8,yes,yes,1.0,2.5,Sometimes,no,2.8,no,0.0,1.7,Sometimes,Public_Transportation,Normal_Weight
2,Male,43.0,1.79,72.2,yes,yes,2.0,3.6,Sometimes,yes,2.5,no,0.5,0.9,no,Automobile,Normal_Weight
3,Male,43.0,1.74,52.0,yes,no,2.0,1.3,Always,no,3.4,yes,1.4,0.1,Frequently,Motorbike,Insufficient_Weight
4,Male,38.0,1.56,63.2,yes,no,2.7,3.4,Frequently,no,2.0,no,2.8,0.3,Frequently,Motorbike,Overweight_Level_I

In [13]:
ob_data.loc[:, 'SMOKE'] = 'yes'
ob_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Male,22.0,1.65,57.1,no,yes,1.5,2.1,Always,yes,3.3,no,0.8,1.5,Frequently,Motorbike,Normal_Weight
1,Male,33.0,1.88,80.8,yes,yes,1.0,2.5,Sometimes,yes,2.8,no,0.0,1.7,Sometimes,Public_Transportation,Normal_Weight
2,Male,43.0,1.79,72.2,yes,yes,2.0,3.6,Sometimes,yes,2.5,no,0.5,0.9,no,Automobile,Normal_Weight
3,Male,43.0,1.74,52.0,yes,no,2.0,1.3,Always,yes,3.4,yes,1.4,0.1,Frequently,Motorbike,Insufficient_Weight
4,Male,38.0,1.56,63.2,yes,no,2.7,3.4,Frequently,yes,2.0,no,2.8,0.3,Frequently,Motorbike,Overweight_Level_I

In [15]:
ob_data.iloc[:, 9] = 'doesnt matter'
ob_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Male,22.0,1.65,57.1,no,yes,1.5,2.1,Always,doesnt matter,3.3,no,0.8,1.5,Frequently,Motorbike,Normal_Weight
1,Male,33.0,1.88,80.8,yes,yes,1.0,2.5,Sometimes,doesnt matter,2.8,no,0.0,1.7,Sometimes,Public_Transportation,Normal_Weight
2,Male,43.0,1.79,72.2,yes,yes,2.0,3.6,Sometimes,doesnt matter,2.5,no,0.5,0.9,no,Automobile,Normal_Weight
3,Male,43.0,1.74,52.0,yes,no,2.0,1.3,Always,doesnt matter,3.4,yes,1.4,0.1,Frequently,Motorbike,Insufficient_Weight
4,Male,38.0,1.56,63.2,yes,no,2.7,3.4,Frequently,doesnt matter,2.0,no,2.8,0.3,Frequently,Motorbike,Overweight_Level_I

In [5]:
ob_data.at[2, 'Obesity'] = 'Not Obese'
ob_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Male,29.0,1.65,57.1,no,yes,1.5,2.1,Always,no,3.3,no,0.8,1.5,Frequently,Motorbike,Normal_Weight
1,Male,33.0,1.88,80.8,yes,yes,1.0,2.5,Sometimes,no,2.8,no,0.0,1.7,Sometimes,Public_Transportation,Normal_Weight
2,Male,43.0,1.79,72.2,yes,yes,2.0,3.6,Sometimes,yes,2.5,no,0.5,0.9,no,Automobile,Not Obese
3,Male,43.0,1.74,52.0,yes,no,2.0,1.3,Always,no,3.4,yes,1.4,0.1,Frequently,Motorbike,Insufficient_Weight
4,Male,38.0,1.56,63.2,yes,no,2.7,3.4,Frequently,no,2.0,no,2.8,0.3,Frequently,Motorbike,Overweight_Level_I

In [7]:
ob_data.iat[2,0] = 'Secret'
ob_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Male,29.0,1.65,57.1,no,yes,1.5,2.1,Always,no,3.3,no,0.8,1.5,Frequently,Motorbike,Normal_Weight
1,Male,33.0,1.88,80.8,yes,yes,1.0,2.5,Sometimes,no,2.8,no,0.0,1.7,Sometimes,Public_Transportation,Normal_Weight
2,Secret,43.0,1.79,72.2,yes,yes,2.0,3.6,Sometimes,yes,2.5,no,0.5,0.9,no,Automobile,Not Obese
3,Male,43.0,1.74,52.0,yes,no,2.0,1.3,Always,no,3.4,yes,1.4,0.1,Frequently,Motorbike,Insufficient_Weight
4,Male,38.0,1.56,63.2,yes,no,2.7,3.4,Frequently,no,2.0,no,2.8,0.3,Frequently,Motorbike,Overweight_Level_I

In [9]:
ob_data['SMOKE'] = 'Yes'
ob_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Male,29.0,1.65,57.1,no,yes,1.5,2.1,Always,Yes,3.3,no,0.8,1.5,Frequently,Motorbike,Normal_Weight
1,Male,33.0,1.88,80.8,yes,yes,1.0,2.5,Sometimes,Yes,2.8,no,0.0,1.7,Sometimes,Public_Transportation,Normal_Weight
2,Secret,43.0,1.79,72.2,yes,yes,2.0,3.6,Sometimes,Yes,2.5,no,0.5,0.9,no,Automobile,Not Obese
3,Male,43.0,1.74,52.0,yes,no,2.0,1.3,Always,Yes,3.4,yes,1.4,0.1,Frequently,Motorbike,Insufficient_Weight
4,Male,38.0,1.56,63.2,yes,no,2.7,3.4,Frequently,Yes,2.0,no,2.8,0.3,Frequently,Motorbike,Overweight_Level_I

In [ ]:
#Updating the column of each row
def increment_by_5(x):
    return x+5;

ob_data['Age'] = ob_data['Age'].apply(increment_by_5)
ob_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Male,74.0,1.65,57.1,no,yes,1.5,2.1,Always,Yes,3.3,no,0.8,1.5,Frequently,Motorbike,Normal_Weight
1,Male,78.0,1.88,80.8,yes,yes,1.0,2.5,Sometimes,Yes,2.8,no,0.0,1.7,Sometimes,Public_Transportation,Normal_Weight
2,Secret,88.0,1.79,72.2,yes,yes,2.0,3.6,Sometimes,Yes,2.5,no,0.5,0.9,no,Automobile,Not Obese
3,Male,88.0,1.74,52.0,yes,no,2.0,1.3,Always,Yes,3.4,yes,1.4,0.1,Frequently,Motorbike,Insufficient_Weight
4,Male,83.0,1.56,63.2,yes,no,2.7,3.4,Frequently,Yes,2.0,no,2.8,0.3,Frequently,Motorbike,Overweight_Level_I

In [28]:
#using lambda function

ob_data['Age'] = ob_data['Age'].apply(lambda x : x-5);
ob_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Male,29.0,1.65,57.1,no,yes,1.5,2.1,Always,Yes,3.3,no,0.8,1.5,Frequently,Motorbike,Normal_Weight
1,Male,33.0,1.88,80.8,yes,yes,1.0,2.5,Sometimes,Yes,2.8,no,0.0,1.7,Sometimes,Public_Transportation,Normal_Weight
2,Secret,43.0,1.79,72.2,yes,yes,2.0,3.6,Sometimes,Yes,2.5,no,0.5,0.9,no,Automobile,Not Obese
3,Male,43.0,1.74,52.0,yes,no,2.0,1.3,Always,Yes,3.4,yes,1.4,0.1,Frequently,Motorbike,Insufficient_Weight
4,Male,38.0,1.56,63.2,yes,no,2.7,3.4,Frequently,Yes,2.0,no,2.8,0.3,Frequently,Motorbike,Overweight_Level_I

In [29]:
ob_data['Age Category'] = ob_data['Age'].apply(lambda x: 'Very young' if x <25 else 'Mature')
ob_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category
0,Male,29.0,1.65,57.1,no,yes,1.5,2.1,Always,Yes,3.3,no,0.8,1.5,Frequently,Motorbike,Normal_Weight,Mature
1,Male,33.0,1.88,80.8,yes,yes,1.0,2.5,Sometimes,Yes,2.8,no,0.0,1.7,Sometimes,Public_Transportation,Normal_Weight,Mature
2,Secret,43.0,1.79,72.2,yes,yes,2.0,3.6,Sometimes,Yes,2.5,no,0.5,0.9,no,Automobile,Not Obese,Mature
3,Male,43.0,1.74,52.0,yes,no,2.0,1.3,Always,Yes,3.4,yes,1.4,0.1,Frequently,Motorbike,Insufficient_Weight,Mature
4,Male,38.0,1.56,63.2,yes,no,2.7,3.4,Frequently,Yes,2.0,no,2.8,0.3,Frequently,Motorbike,Overweight_Level_I,Mature

In [31]:
import numpy as np

In [34]:
ob_data['New Age Category'] = np.where(ob_data['Age'] < 25, 'Very Young', 'Mature')
ob_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category,New Age Category
0,Male,29.0,1.65,57.1,no,yes,1.5,2.1,Always,Yes,3.3,no,0.8,1.5,Frequently,Motorbike,Normal_Weight,Mature,Mature
1,Male,33.0,1.88,80.8,yes,yes,1.0,2.5,Sometimes,Yes,2.8,no,0.0,1.7,Sometimes,Public_Transportation,Normal_Weight,Mature,Mature
2,Secret,43.0,1.79,72.2,yes,yes,2.0,3.6,Sometimes,Yes,2.5,no,0.5,0.9,no,Automobile,Not Obese,Mature,Mature
3,Male,43.0,1.74,52.0,yes,no,2.0,1.3,Always,Yes,3.4,yes,1.4,0.1,Frequently,Motorbike,Insufficient_Weight,Mature,Mature
4,Male,38.0,1.56,63.2,yes,no,2.7,3.4,Frequently,Yes,2.0,no,2.8,0.3,Frequently,Motorbike,Overweight_Level_I,Mature,Mature